/*
 * Bravo API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models::{ChatJsonResponseChoicesInner, ChatJsonResponseUsage};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatJsonResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "object")]
    pub object: Object,
    #[serde(rename = "created")]
    pub created: f64,
    #[serde(rename = "model")]
    pub model: String,
    #[serde(rename = "choices")]
    pub choices: Vec<ChatJsonResponseChoicesInner>,
    #[serde(rename = "usage")]
    pub usage: Box<ChatJsonResponseUsage>,
}

impl ChatJsonResponse {
    pub fn new(
        id: String,
        object: Object,
        created: f64,
        model: String,
        choices: Vec<ChatJsonResponseChoicesInner>,
        usage: ChatJsonResponseUsage,
    ) -> ChatJsonResponse {
        ChatJsonResponse {
            id,
            object,
            created,
            model,
            choices,
            usage: Box::new(usage),
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "chat.completion")]
    ChatCompletion,
}

impl Default for Object {
    fn default() -> Object {
        Self::ChatCompletion
    }
}
