/*
 * Bravo API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models::FileUploadResponseFile;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileUploadResponse {
    #[serde(rename = "file")]
    pub file: Box<FileUploadResponseFile>,
}

impl FileUploadResponse {
    pub fn new(file: FileUploadResponseFile) -> FileUploadResponse {
        FileUploadResponse {
            file: Box::new(file),
        }
    }
}
