/*
 * Bravo API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models::openapi;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BravoChatRequestMessage {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "role")]
    pub role: Role,
    #[serde(rename = "parts")]
    pub parts: Vec<openapi::BravoChatRequestMessagePartsInner>,
}

impl BravoChatRequestMessage {
    pub fn new(
        id: uuid::Uuid,
        role: Role,
        parts: Vec<openapi::BravoChatRequestMessagePartsInner>,
    ) -> BravoChatRequestMessage {
        BravoChatRequestMessage { id, role, parts }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "user")]
    User,
}

impl Default for Role {
    fn default() -> Role {
        Self::User
    }
}
