/*
 * Bravo API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models::openapi;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatJsonResponseChoicesInnerMessage {
    #[serde(rename = "role")]
    pub role: Role,
    #[serde(rename = "content", deserialize_with = "Option::deserialize")]
    pub content: Option<String>,
}

impl ChatJsonResponseChoicesInnerMessage {
    pub fn new(role: Role, content: Option<String>) -> ChatJsonResponseChoicesInnerMessage {
        ChatJsonResponseChoicesInnerMessage {
            role,
            content,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "assistant")]
    Assistant,
}

impl Default for Role {
    fn default() -> Role {
        Self::Assistant
    }
}

