/*
 * Bravo API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models::openapi;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatsListResponse {
    #[serde(rename = "chats")]
    pub chats: Vec<openapi::ChatsListResponseChatsInner>,
    #[serde(
        rename = "nextCursor",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub next_cursor: Option<Option<String>>,
}

impl ChatsListResponse {
    pub fn new(chats: Vec<openapi::ChatsListResponseChatsInner>) -> ChatsListResponse {
        ChatsListResponse {
            chats,
            next_cursor: None,
        }
    }
}
