/*
 * Bravo API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models::openapi;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorEnvelope {
    #[serde(rename = "error")]
    pub error: Box<openapi::ErrorEnvelopeError>,
}

impl ErrorEnvelope {
    pub fn new(error: openapi::ErrorEnvelopeError) -> ErrorEnvelope {
        ErrorEnvelope {
            error: Box::new(error),
        }
    }
}
