/*
 * Bravo API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models::openapi;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListModels200ResponseModelsInnerCapabilities {
    #[serde(rename = "tools")]
    pub tools: bool,
    #[serde(rename = "jsonMode")]
    pub json_mode: bool,
    #[serde(rename = "reasoning")]
    pub reasoning: bool,
}

impl ListModels200ResponseModelsInnerCapabilities {
    pub fn new(tools: bool, json_mode: bool, reasoning: bool) -> ListModels200ResponseModelsInnerCapabilities {
        ListModels200ResponseModelsInnerCapabilities {
            tools,
            json_mode,
            reasoning,
        }
    }
}

