/*
 * Bravo API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models::openapi;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListModels200Response {
    #[serde(rename = "models")]
    pub models: Vec<openapi::ListModels200ResponseModelsInner>,
    #[serde(
        rename = "nextCursor",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub next_cursor: Option<Option<String>>,
}

impl ListModels200Response {
    pub fn new(models: Vec<openapi::ListModels200ResponseModelsInner>) -> ListModels200Response {
        ListModels200Response {
            models,
            next_cursor: None,
        }
    }
}
