/*
 * Bravo API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models::openapi;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpenAiChatRequest {
    #[serde(rename = "model")]
    pub model: String,
    #[serde(rename = "messages")]
    pub messages: Vec<openapi::OpenAiChatRequestMessagesInner>,
    #[serde(rename = "stream", skip_serializing_if = "Option::is_none")]
    pub stream: Option<bool>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Box<openapi::OpenAiChatRequestMetadata>>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<String>,
}

impl OpenAiChatRequest {
    pub fn new(
        model: String,
        messages: Vec<openapi::OpenAiChatRequestMessagesInner>,
    ) -> OpenAiChatRequest {
        OpenAiChatRequest {
            model,
            messages,
            stream: None,
            metadata: None,
            user: None,
        }
    }
}
