/*
 * Bravo API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models::openapi;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostChatRequest {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "message")]
    pub message: Box<openapi::BravoChatRequestMessage>,
    #[serde(rename = "selectedChatModel", skip_serializing_if = "Option::is_none")]
    pub selected_chat_model: Option<SelectedChatModel>,
    #[serde(rename = "selectedVisibilityType")]
    pub selected_visibility_type: SelectedVisibilityType,
    #[serde(rename = "selectedModule", skip_serializing_if = "Option::is_none")]
    pub selected_module: Option<SelectedModule>,
    #[serde(rename = "userName", skip_serializing_if = "Option::is_none")]
    pub user_name: Option<String>,
    #[serde(rename = "promptMode", skip_serializing_if = "Option::is_none")]
    pub prompt_mode: Option<PromptMode>,
    #[serde(
        rename = "systemPromptOverride",
        skip_serializing_if = "Option::is_none"
    )]
    pub system_prompt_override: Option<String>,
    #[serde(
        rename = "generalPromptSelection",
        skip_serializing_if = "Option::is_none"
    )]
    pub general_prompt_selection: Option<Box<openapi::BravoChatRequestGeneralPromptSelection>>,
    #[serde(
        rename = "modulePromptSelections",
        skip_serializing_if = "Option::is_none"
    )]
    pub module_prompt_selections: Option<
        std::collections::HashMap<String, openapi::BravoChatRequestModulePromptSelectionsValue>,
    >,
    #[serde(rename = "stream", skip_serializing_if = "Option::is_none")]
    pub stream: Option<bool>,
    #[serde(rename = "response", skip_serializing_if = "Option::is_none")]
    pub response: Option<Response>,
    #[serde(rename = "model")]
    pub model: String,
    #[serde(rename = "messages")]
    pub messages: Vec<openapi::OpenAiChatRequestMessagesInner>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Box<openapi::OpenAiChatRequestMetadata>>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<String>,
}

impl PostChatRequest {
    pub fn new(
        id: uuid::Uuid,
        message: openapi::BravoChatRequestMessage,
        selected_visibility_type: SelectedVisibilityType,
        model: String,
        messages: Vec<openapi::OpenAiChatRequestMessagesInner>,
    ) -> PostChatRequest {
        PostChatRequest {
            id,
            message: Box::new(message),
            selected_chat_model: None,
            selected_visibility_type,
            selected_module: None,
            user_name: None,
            prompt_mode: None,
            system_prompt_override: None,
            general_prompt_selection: None,
            module_prompt_selections: None,
            stream: None,
            response: None,
            model,
            messages,
            metadata: None,
            user: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SelectedChatModel {
    #[serde(rename = "bravo-fast")]
    BravoFast,
    #[serde(rename = "bravo")]
    Bravo,
    #[serde(rename = "bravo-pro")]
    BravoPro,
}

impl Default for SelectedChatModel {
    fn default() -> SelectedChatModel {
        Self::BravoFast
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SelectedVisibilityType {
    #[serde(rename = "public")]
    Public,
    #[serde(rename = "private")]
    Private,
}

impl Default for SelectedVisibilityType {
    fn default() -> SelectedVisibilityType {
        Self::Public
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SelectedModule {
    #[serde(rename = "spending")]
    Spending,
    #[serde(rename = "saving")]
    Saving,
    #[serde(rename = "debt")]
    Debt,
    #[serde(rename = "retirement")]
    Retirement,
    #[serde(rename = "planning_insurance")]
    PlanningInsurance,
    #[serde(rename = "planning_estate")]
    PlanningEstate,
}

impl Default for SelectedModule {
    fn default() -> SelectedModule {
        Self::Spending
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PromptMode {
    #[serde(rename = "standard")]
    Standard,
    #[serde(rename = "omniprompt")]
    Omniprompt,
}

impl Default for PromptMode {
    fn default() -> PromptMode {
        Self::Standard
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Response {
    #[serde(rename = "sse")]
    Sse,
    #[serde(rename = "json")]
    Json,
}

impl Default for Response {
    fn default() -> Response {
        Self::Sse
    }
}
