/*
 * Bravo API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models::openapi;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserContextResponseMetadata {
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(rename = "cached_at", skip_serializing_if = "Option::is_none")]
    pub cached_at: Option<String>,
    #[serde(rename = "ttl_seconds", skip_serializing_if = "Option::is_none")]
    pub ttl_seconds: Option<f64>,
}

impl UserContextResponseMetadata {
    pub fn new() -> UserContextResponseMetadata {
        UserContextResponseMetadata {
            source: None,
            cached_at: None,
            ttl_seconds: None,
        }
    }
}

