/*
 * Bravo API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Debug, Clone)]
pub struct Configuration {
    pub base_path: String,
    pub user_agent: Option<String>,
    pub client: reqwest::Client,
    pub basic_auth: Option<BasicAuth>,
    pub oauth_access_token: Option<String>,
    pub bearer_access_token: Option<String>,
    pub api_key: Option<ApiKey>,
}

pub type BasicAuth = (String, Option<String>);

#[derive(Debug, Clone)]
pub struct ApiKey {
    pub prefix: Option<String>,
    pub key: String,
}

impl Configuration {
    pub fn new() -> Configuration {
        Configuration::default()
    }
}

const DEV_TOKEN: &str = "USER_TOKEN_HERE";

impl Default for Configuration {
    fn default() -> Self {
        Configuration {
            base_path: "http://localhost:3000".to_owned(),
            user_agent: Some("OpenAPI-Generator/1.0.0/rust".to_owned()),
            client: {
                let mut headers = reqwest::header::HeaderMap::new();
                headers.insert(
                    reqwest::header::AUTHORIZATION,
                    format!("Bearer {}", DEV_TOKEN).parse().unwrap(),
                );

                reqwest::Client::builder()
                    .default_headers(headers)
                    .build()
                    .unwrap()
            },
            basic_auth: None,
            oauth_access_token: None,
            bearer_access_token: Some(DEV_TOKEN.to_string()),
            api_key: None,
        }
    }
}
