/*
 * Bravo API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BravoChatRequestMessagePartsInnerAnyOf1 {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "mediaType")]
    pub media_type: MediaType,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "url")]
    pub url: String,
}

impl BravoChatRequestMessagePartsInnerAnyOf1 {
    pub fn new(r#type: Type, media_type: MediaType, name: String, url: String) -> BravoChatRequestMessagePartsInnerAnyOf1 {
        BravoChatRequestMessagePartsInnerAnyOf1 {
            r#type,
            media_type,
            name,
            url,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "file")]
    File,
}

impl Default for Type {
    fn default() -> Type {
        Self::File
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MediaType {
    #[serde(rename = "image/jpeg")]
    ImageSlashJpeg,
    #[serde(rename = "image/png")]
    ImageSlashPng,
}

impl Default for MediaType {
    fn default() -> MediaType {
        Self::ImageSlashJpeg
    }
}

