/*
 * Bravo API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatsListResponseChatsInnerMetadata {
    #[serde(rename = "module", skip_serializing_if = "Option::is_none")]
    pub module: Option<String>,
    #[serde(rename = "personaId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub persona_id: Option<Option<String>>,
}

impl ChatsListResponseChatsInnerMetadata {
    pub fn new() -> ChatsListResponseChatsInnerMetadata {
        ChatsListResponseChatsInnerMetadata {
            module: None,
            persona_id: None,
        }
    }
}

