/*
 * Bravo API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatMessagesResponseMessagesInner {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<Role>,
    #[serde(rename = "parts")]
    pub parts: Vec<models::OpenAiChatRequestMessagesInnerContentAnyOfInner>,
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
}

impl ChatMessagesResponseMessagesInner {
    pub fn new(id: String, parts: Vec<models::OpenAiChatRequestMessagesInnerContentAnyOfInner>) -> ChatMessagesResponseMessagesInner {
        ChatMessagesResponseMessagesInner {
            id,
            role: None,
            parts,
            created_at: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "user")]
    User,
    #[serde(rename = "assistant")]
    Assistant,
    #[serde(rename = "system")]
    System,
}

impl Default for Role {
    fn default() -> Role {
        Self::User
    }
}

