/*
 * Bravo API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatJsonResponseChoicesInner {
    #[serde(rename = "index")]
    pub index: f64,
    #[serde(rename = "message")]
    pub message: Box<models::ChatJsonResponseChoicesInnerMessage>,
    #[serde(rename = "finish_reason", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub finish_reason: Option<Option<String>>,
}

impl ChatJsonResponseChoicesInner {
    pub fn new(index: f64, message: models::ChatJsonResponseChoicesInnerMessage) -> ChatJsonResponseChoicesInner {
        ChatJsonResponseChoicesInner {
            index,
            message: Box::new(message),
            finish_reason: None,
        }
    }
}

