/*
 * Bravo API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteChatResponse {
    #[serde(rename = "deleted")]
    pub deleted: bool,
}

impl DeleteChatResponse {
    pub fn new(deleted: bool) -> DeleteChatResponse {
        DeleteChatResponse {
            deleted,
        }
    }
}

