/*
 * Bravo API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetModel200Response {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "family")]
    pub family: String,
    #[serde(rename = "modality")]
    pub modality: Vec<Modality>,
    #[serde(rename = "capabilities")]
    pub capabilities: Box<models::ListModels200ResponseModelsInnerCapabilities>,
    #[serde(rename = "contextWindow")]
    pub context_window: f64,
    #[serde(rename = "maxOutputTokens")]
    pub max_output_tokens: f64,
    #[serde(rename = "latencyClass")]
    pub latency_class: LatencyClass,
    #[serde(rename = "tier")]
    pub tier: Tier,
    #[serde(rename = "aliases", skip_serializing_if = "Option::is_none")]
    pub aliases: Option<Vec<String>>,
    #[serde(rename = "default", skip_serializing_if = "Option::is_none")]
    pub default: Option<bool>,
    #[serde(rename = "deprecatedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub deprecated_at: Option<Option<String>>,
    #[serde(rename = "policy", skip_serializing_if = "Option::is_none")]
    pub policy: Option<Box<models::ListModels200ResponseModelsInnerPolicy>>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "compatibleTools", skip_serializing_if = "Option::is_none")]
    pub compatible_tools: Option<Vec<String>>,
    #[serde(rename = "availability", skip_serializing_if = "Option::is_none")]
    pub availability: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl GetModel200Response {
    pub fn new(id: String, label: String, family: String, modality: Vec<Modality>, capabilities: models::ListModels200ResponseModelsInnerCapabilities, context_window: f64, max_output_tokens: f64, latency_class: LatencyClass, tier: Tier) -> GetModel200Response {
        GetModel200Response {
            id,
            label,
            family,
            modality,
            capabilities: Box::new(capabilities),
            context_window,
            max_output_tokens,
            latency_class,
            tier,
            aliases: None,
            default: None,
            deprecated_at: None,
            policy: None,
            metadata: None,
            compatible_tools: None,
            availability: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Modality {
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "vision")]
    Vision,
    #[serde(rename = "audio")]
    Audio,
    #[serde(rename = "multimodal")]
    Multimodal,
}

impl Default for Modality {
    fn default() -> Modality {
        Self::Text
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LatencyClass {
    #[serde(rename = "low")]
    Low,
    #[serde(rename = "medium")]
    Medium,
    #[serde(rename = "high")]
    High,
}

impl Default for LatencyClass {
    fn default() -> LatencyClass {
        Self::Low
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Tier {
    #[serde(rename = "fast")]
    Fast,
    #[serde(rename = "standard")]
    Standard,
    #[serde(rename = "pro")]
    Pro,
}

impl Default for Tier {
    fn default() -> Tier {
        Self::Fast
    }
}

