/*
 * Bravo API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListModels200ResponseModelsInnerPolicy {
    #[serde(rename = "allowedTools", skip_serializing_if = "Option::is_none")]
    pub allowed_tools: Option<Vec<String>>,
    #[serde(rename = "modules", skip_serializing_if = "Option::is_none")]
    pub modules: Option<Vec<String>>,
}

impl ListModels200ResponseModelsInnerPolicy {
    pub fn new() -> ListModels200ResponseModelsInnerPolicy {
        ListModels200ResponseModelsInnerPolicy {
            allowed_tools: None,
            modules: None,
        }
    }
}

