/*
 * Bravo API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpenAiChatRequestMessagesInner {
    #[serde(rename = "role")]
    pub role: Role,
    #[serde(rename = "content")]
    pub content: Box<models::OpenAiChatRequestMessagesInnerContent>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl OpenAiChatRequestMessagesInner {
    pub fn new(role: Role, content: models::OpenAiChatRequestMessagesInnerContent) -> OpenAiChatRequestMessagesInner {
        OpenAiChatRequestMessagesInner {
            role,
            content: Box::new(content),
            name: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "system")]
    System,
    #[serde(rename = "user")]
    User,
    #[serde(rename = "assistant")]
    Assistant,
}

impl Default for Role {
    fn default() -> Role {
        Self::System
    }
}

