/*
 * Bravo API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserContextResponse {
    #[serde(rename = "user_context")]
    pub user_context: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "persona", skip_serializing_if = "Option::is_none")]
    pub persona: Option<Box<models::UserContextResponsePersona>>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Box<models::UserContextResponseMetadata>>,
}

impl UserContextResponse {
    pub fn new(user_context: std::collections::HashMap<String, serde_json::Value>) -> UserContextResponse {
        UserContextResponse {
            user_context,
            persona: None,
            metadata: None,
        }
    }
}

